name: Test

on: push

jobs:
  test:
    name: go test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["amd64", "386", "arm", "arm64"]
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run:  go test ./...
        env:
          GOARCH: ${{ matrix.arch }}
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest
